# Generated by Django 6.0 on 2026-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hover_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
