# Generated by Django 6.0 on 2026-07-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0004_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecommendation',
            name='mood',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('sad', 'Sad'), ('chill', 'Chill'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendations', to='diary_project.year'),
        ),
    ]
