# Generated by Django 6.0 on 2026-07-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_hover_profile_picture'),
        ('diary_project', '0005_alter_songrecommendation_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrecommendation',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='recommended_to',
        ),
        migrations.AddField(
            model_name='songrecommendation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_songs', to='accounts.userprofile'),
        ),
    ]
