# Generated by Django 6.0 on 2026-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0006_remove_songrecommendation_recommended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='completed_by_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='completed_by_shaira',
            field=models.BooleanField(default=False),
        ),
    ]
