# Generated by Django 6.0 on 2026-07-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_couple'),
        ('diary_project', '0007_bucketlistitem_completed_by_me_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animecategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='animecategory',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_categories', to='diary_project.year'),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to='diary_project.year'),
        ),
        migrations.AddConstraint(
            model_name='animecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('couple', 'year', 'name', 'media_type'), name='unique_anime_category_per_year'),
        ),
        migrations.AddConstraint(
            model_name='animecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('couple', 'name', 'media_type'), name='unique_anime_category_global'),
        ),
    ]
