# Generated by Django 6.0 on 2026-07-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_couple'),
        ('diary_project', '0008_alter_animecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couplegamescore',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='couplegamescore',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='diary_project.year'),
        ),
        migrations.AddConstraint(
            model_name='couplegamescore',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('couple', 'year', 'game_name'), name='unique_game_score_per_year'),
        ),
        migrations.AddConstraint(
            model_name='couplegamescore',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('couple', 'game_name'), name='unique_game_score_global'),
        ),
    ]
